import { useCallback, useEffect, useState } from "react";
import { getJson } from "../services/api.js";
export default function AdministrationPage({ cameras, cameraForm, updateForm, addCamera, editCamera, deleteCamera, PanelHeader, adminToken }) {
  const [errors, setErrors] = useState([]); const [status, setStatus] = useState("");
  const loadErrors = useCallback(async () => { try { const data = await getJson("/api/admin/errors?limit=100", { headers: { Authorization: `Bearer ${adminToken}` } }); setErrors(data.data || []); } catch (error) { setStatus(error.message); } }, [adminToken]);
  useEffect(() => { const initial = setTimeout(loadErrors, 0); const timer = setInterval(loadErrors, 10000); return () => { clearTimeout(initial); clearInterval(timer); }; }, [loadErrors]);
  const acknowledge = async (id) => { await fetch(`${import.meta.env.VITE_API_URL || `http://${window.location.hostname || "localhost"}:5001`}/api/admin/errors/${id}`, { method: "PATCH", headers: { Authorization: `Bearer ${adminToken}` } }); loadErrors(); };
  return <div className="page-view"><div className="page-heading"><div><small>OPERATIONS / ADMINISTRATION</small><h1>Administration</h1><p>Registry controls and centralized error review.</p></div><span className="page-badge">{cameras.length} registered</span></div><section className="panel admin-panel"><PanelHeader title="Camera onboarding" action="Protected operator action" /><form onSubmit={addCamera} className="admin-form">{["camera_id", "name", "location_name", "latitude", "longitude"].map((field) => <input key={field} required={field !== "name" && field !== "location_name"} placeholder={field.replaceAll("_", " ")} value={cameraForm[field]} onChange={updateForm(field)} />)}<button type="submit">Register camera</button></form></section><section className="panel registry-panel"><PanelHeader title="System error center" action={`${errors.filter((e) => !e.acknowledged).length} unacknowledged`} />{status && <p className="error">{status}</p>}<div className="table-wrap"><table><thead><tr><th>Time</th><th>Source</th><th>Route</th><th>Message</th><th>Status</th><th>Action</th></tr></thead><tbody>{errors.map((error) => <tr key={error.id}><td>{new Date(error.created_at).toLocaleString()}</td><td>{error.source}</td><td>{error.route || "—"}</td><td>{error.message}</td><td>{error.acknowledged ? "Acknowledged" : "Open"}</td><td>{!error.acknowledged && <button className="table-action" onClick={() => acknowledge(error.id)}>Acknowledge</button>}</td></tr>)}</tbody></table>{!errors.length && <div className="empty-state">No recorded platform errors.</div>}</div></section><section className="panel registry-panel"><PanelHeader title="Registered cameras" action="CRUD" /><div className="table-wrap"><table><thead><tr><th>Camera ID</th><th>Name</th><th>Location</th><th>Status</th><th>Actions</th></tr></thead><tbody>{cameras.map((camera) => <tr key={camera.id}><td><b>{camera.camera_id}</b><small>{camera.id}</small></td><td>{camera.name || "Unnamed"}</td><td>{camera.location_name || "Unavailable"}</td><td><span className="table-status">{camera.health_status || camera.status || "UNKNOWN"}</span></td><td><button className="table-action" onClick={() => editCamera(camera)}>Rename</button><button className="table-action danger" onClick={() => deleteCamera(camera.id)}>Delete</button></td></tr>)}</tbody></table>{!cameras.length && <div className="empty-state">No cameras are registered.</div>}</div></section></div>;
}
